"""
FastAPI app entrypoint.

Phase 1 / Step 4 — adds POST /ingest (JSON) and POST /ingest/file (multipart).

Routes:
- GET  /health         — liveness probe
- POST /ingest         — JSON body: {source, text, metadata?}
- POST /ingest/file    — multipart: file=, source=
- GET  /docs           — auto-generated by FastAPI

Real /query endpoint lands in Step 5.
"""

from typing import Any

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from pydantic import BaseModel, Field

from app import ingest as ingest_lib


app = FastAPI(
    title="rag-api",
    description="Retrieval-Augmented Generation API. Phase 1 MVP.",
    version="0.2.0",
)


# --------------------------------------------------------------------------
# Schemas
# --------------------------------------------------------------------------

class IngestTextRequest(BaseModel):
    """JSON body for POST /ingest. Pydantic enforces non-empty source/text."""
    source: str = Field(..., min_length=1, max_length=512,
                        description="Canonical doc id. Re-ingest replaces by source.")
    text: str = Field(..., min_length=1,
                      description="Raw text to chunk + embed.")
    metadata: dict[str, Any] | None = Field(default=None,
                                            description="Arbitrary JSONB metadata.")


class IngestResponse(BaseModel):
    """Standard response shape for both ingest paths."""
    source: str
    chunks_created: int
    chunks_replaced: int  # rows wiped by DELETE-by-source step


# --------------------------------------------------------------------------
# Routes
# --------------------------------------------------------------------------

@app.get("/health", tags=["meta"])
def health() -> dict:
    """Liveness probe. Returns 200 if the FastAPI process is up."""
    return {"status": "ok", "service": "rag-api", "version": "0.2.0"}


@app.post("/ingest", response_model=IngestResponse, tags=["ingest"])
def ingest_text_endpoint(payload: IngestTextRequest) -> IngestResponse:
    """
    Ingest raw text via JSON body.

    Pydantic validates source/text non-empty BEFORE the handler runs;
    malformed payloads return 422 automatically.
    """
    result = ingest_lib.ingest_text(
        source=payload.source,
        text=payload.text,
        metadata=payload.metadata,
    )
    return IngestResponse(
        source=result.source,
        chunks_created=result.chunks_created,
        chunks_replaced=result.chunks_replaced,
    )


@app.post("/ingest/file", response_model=IngestResponse, tags=["ingest"])
def ingest_file_endpoint(
    source: str = Form(..., min_length=1, max_length=512),
    file: UploadFile = File(...),
) -> IngestResponse:
    """
    Ingest a file (PDF or text) via multipart upload.

    Form fields:
    - source: canonical id for this doc (used for re-ingest)
    - file: must be application/pdf or text/plain, <= 10MB

    Mime/size violations -> 400 (caught from ValueError in ingest_lib).
    """
    # file.file is the underlying SpooledTemporaryFile (sync read is fine
    # because this is a sync handler running in FastAPI's thread pool).
    file_bytes = file.file.read()
    try:
        result = ingest_lib.ingest_file(
            source=source,
            file_bytes=file_bytes,
            content_type=file.content_type or "",
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    return IngestResponse(
        source=result.source,
        chunks_created=result.chunks_created,
        chunks_replaced=result.chunks_replaced,
    )
