"""
FastAPI app entrypoint.

Phase 1 / Step 2 minimal version:
- /health returns 200 if the process is alive
- /docs auto-generated by FastAPI

Real endpoints (/ingest, /query) land in Steps 4 and 5.
"""

from fastapi import FastAPI

app = FastAPI(
    title="rag-api",
    description="Retrieval-Augmented Generation API. Phase 1 MVP.",
    version="0.1.0",
)


@app.get("/health", tags=["meta"])
def health() -> dict:
    """
    Liveness probe.

    Returns 200 if the FastAPI process is up. Does NOT check db connectivity
    yet — that gets added in Step 3 once we have a connection pool.
    """
    return {"status": "ok", "service": "rag-api", "version": "0.1.0"}
