"""
FastAPI app entrypoint.

Phase 1 / Step 5 — adds POST /query/retrieve and POST /query/answer.

Routes:
- GET  /health           — liveness probe
- POST /ingest           — JSON body: {source, text, metadata?}
- POST /ingest/file      — multipart: file=, source=
- POST /query/retrieve   — JSON body: {question, top_k?} -> raw chunks
- POST /query/answer     — JSON body: {question, top_k?} -> LLM-synthesized answer
- GET  /docs             — auto-generated by FastAPI
"""

from typing import Any

import anthropic
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from pydantic import BaseModel, Field

from app import ingest as ingest_lib
from app import retrieval as retrieval_lib
from app import synthesis as synthesis_lib


app = FastAPI(
    title="rag-api",
    description="Retrieval-Augmented Generation API. Phase 1 MVP.",
    version="0.3.0",
)


# --------------------------------------------------------------------------
# Schemas
# --------------------------------------------------------------------------

class IngestTextRequest(BaseModel):
    """JSON body for POST /ingest. Pydantic enforces non-empty source/text."""
    source: str = Field(..., min_length=1, max_length=512,
                        description="Canonical doc id. Re-ingest replaces by source.")
    text: str = Field(..., min_length=1,
                      description="Raw text to chunk + embed.")
    metadata: dict[str, Any] | None = Field(default=None,
                                            description="Arbitrary JSONB metadata.")


class IngestResponse(BaseModel):
    """Standard response shape for both ingest paths."""
    source: str
    chunks_created: int
    chunks_replaced: int  # rows wiped by DELETE-by-source step


class QueryRequest(BaseModel):
    """JSON body shared by /query/retrieve and /query/answer."""
    question: str = Field(..., min_length=1, max_length=2000,
                          description="Natural-language query.")
    top_k: int | None = Field(default=None, ge=1, le=50,
                              description="Override env-default top-K.")


class RetrievedChunkOut(BaseModel):
    """Wire-format for one retrieved chunk."""
    source: str
    chunk_text: str
    distance: float  # cosine distance, lower = more similar


class QueryRetrieveResponse(BaseModel):
    """Response for /query/retrieve — raw chunks, no LLM."""
    question: str
    top_k: int
    chunks: list[RetrievedChunkOut]


class QueryAnswerResponse(BaseModel):
    """Response for /query/answer — LLM-synthesized answer + provenance."""
    question: str
    answer: str
    model: str
    top_k: int
    chunks_used: list[RetrievedChunkOut]
    input_tokens: int
    output_tokens: int


# --------------------------------------------------------------------------
# Routes
# --------------------------------------------------------------------------

@app.get("/health", tags=["meta"])
def health() -> dict:
    """Liveness probe. Returns 200 if the FastAPI process is up."""
    return {"status": "ok", "service": "rag-api", "version": app.version}


@app.post("/ingest", response_model=IngestResponse, tags=["ingest"])
def ingest_text_endpoint(payload: IngestTextRequest) -> IngestResponse:
    """
    Ingest raw text via JSON body.

    Pydantic validates source/text non-empty BEFORE the handler runs;
    malformed payloads return 422 automatically.
    """
    result = ingest_lib.ingest_text(
        source=payload.source,
        text=payload.text,
        metadata=payload.metadata,
    )
    return IngestResponse(
        source=result.source,
        chunks_created=result.chunks_created,
        chunks_replaced=result.chunks_replaced,
    )


@app.post("/ingest/file", response_model=IngestResponse, tags=["ingest"])
def ingest_file_endpoint(
    source: str = Form(..., min_length=1, max_length=512),
    file: UploadFile = File(...),
) -> IngestResponse:
    """
    Ingest a file (PDF or text) via multipart upload.

    Form fields:
    - source: canonical id for this doc (used for re-ingest)
    - file: must be application/pdf or text/plain, <= 10MB

    Mime/size violations -> 400 (caught from ValueError in ingest_lib).
    """
    # file.file is the underlying SpooledTemporaryFile (sync read is fine
    # because this is a sync handler running in FastAPI's thread pool).
    file_bytes = file.file.read()
    try:
        result = ingest_lib.ingest_file(
            source=source,
            file_bytes=file_bytes,
            content_type=file.content_type or "",
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    return IngestResponse(
        source=result.source,
        chunks_created=result.chunks_created,
        chunks_replaced=result.chunks_replaced,
    )


@app.post("/query/retrieve", response_model=QueryRetrieveResponse, tags=["query"])
def query_retrieve_endpoint(payload: QueryRequest) -> QueryRetrieveResponse:
    """
    Retrieve top-K chunks most similar to `question`. No LLM call.

    Cheap path (no Anthropic tokens spent) — useful for debugging
    retrieval quality and for clients that want their own composition
    layer on top of raw chunks.
    """
    try:
        chunks = retrieval_lib.retrieve(
            question=payload.question,
            top_k=payload.top_k,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    return QueryRetrieveResponse(
        question=payload.question,
        top_k=len(chunks),
        chunks=[
            RetrievedChunkOut(
                source=c.source,
                chunk_text=c.chunk_text,
                distance=c.distance,
            )
            for c in chunks
        ],
    )


@app.post("/query/answer", response_model=QueryAnswerResponse, tags=["query"])
def query_answer_endpoint(payload: QueryRequest) -> QueryAnswerResponse:
    """
    Retrieve top-K chunks AND synthesize an answer via Anthropic.

    Failure modes mapped to HTTP:
    - empty/invalid question        -> 400
    - Anthropic auth failure        -> 502 (upstream auth, not our auth)
    - Anthropic rate limit/timeout  -> 504
    - Other Anthropic API errors    -> 502
    """
    try:
        chunks = retrieval_lib.retrieve(
            question=payload.question,
            top_k=payload.top_k,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    try:
        result = synthesis_lib.synthesize(
            question=payload.question,
            chunks=chunks,
        )
    except anthropic.AuthenticationError as e:
        raise HTTPException(status_code=502, detail=f"Anthropic auth failed: {e}")
    except (anthropic.APITimeoutError, anthropic.RateLimitError) as e:
        raise HTTPException(status_code=504, detail=f"Anthropic upstream slow: {e}")
    except anthropic.APIError as e:
        raise HTTPException(status_code=502, detail=f"Anthropic upstream error: {e}")

    return QueryAnswerResponse(
        question=payload.question,
        answer=result.answer,
        model=result.model,
        top_k=len(result.chunks_used),
        chunks_used=[
            RetrievedChunkOut(
                source=c.source,
                chunk_text=c.chunk_text,
                distance=c.distance,
            )
            for c in result.chunks_used
        ],
        input_tokens=result.input_tokens,
        output_tokens=result.output_tokens,
    )
